services:
  node-1:
    build: .
    ports:
      - "8090:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.distributor.rule=Host(`distributor.stanrunge.dev`)"
      - "traefik.http.routers.distributor.entrypoints=web,websecure"
      - "traefik.http.routers.distributor.tls.certresolver=myresolver"
      - "traefik.http.services.distributor.loadbalancer.server.port=8080"
    networks:
      distributor_net:
        ipv4_address: 172.16.238.10
      traefik_net:

  node-2:
    build: .
    networks:
      distributor_net:
        ipv4_address: 172.16.238.11
      traefik_net:

  node-3:
    build: .
    networks:
      distributor_net:
        ipv4_address: 172.16.238.12
      traefik_net:

networks:
  distributor_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

  traefik_net:
    external: true
